# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'sphtech' do
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'SDVersion'
    pod 'Masonry'
    
    pod 'UIAlertController+Blocks'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'
    pod 'ImageZoomViewer'
    pod 'DSBarChart', '~> 0.4.0'
end


target 'sphtechTests' do
    
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'SDVersion'
    pod 'Masonry'
    
    pod 'UIAlertController+Blocks'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'
    pod 'ImageZoomViewer'
    pod 'DSBarChart', '~> 0.4.0'
    
end

target 'sphtechRestTests' do
    
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'SDVersion'
    pod 'Masonry'
    
    pod 'UIAlertController+Blocks'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'
    pod 'ImageZoomViewer'
    pod 'DSBarChart', '~> 0.4.0'
    
end
