# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sphtech' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sphtech

  target 'sphtechTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'SDVersion'
    pod 'Masonry'

    pod 'UIAlertController+Blocks'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'

  end

  target 'sphtechUITests' do
    inherit! :search_paths
    # Pods for testing

    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'SDVersion'
    pod 'Masonry'

    pod 'UIAlertController+Blocks'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'

  end

end
